"""unique constraint on projects.github_repo_url

Revision ID: 6e7a0b9e6548
Revises: 87ac3d6b630a
Create Date: 2026-09-03 00:04:46.602445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7a0b9e6548'
down_revision: Union[str, None] = '87ac3d6b630a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_projects_github_repo_url', 'projects', ['github_repo_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_github_repo_url', 'projects', type_='unique')
    # ### end Alembic commands ###
